# Generated by Django 5.2.6 on 2025-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adapplication_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
