# Generated by Django 5.2.6 on 2025-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertisementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(upload_to='ad_images/'),
        ),
    ]
